### PR TITLE
Fix `TIDY_INSTALL_LOC` resolution on Windows

### LINKED ISSUE #103: `Error: Worker not found`
I've been using an old version of tidy for a while, 0.7 I think, just upgraded and now I get this:

```
file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:15316
                  throw util.fromLeft(step3);
                  ^

Error: Worker not found
    at error (file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:5604:10)
    at file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:23456:283
    at file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:23462:18
    at run3 (file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:15120:23)
    at file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:15182:23
    at drain (file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:15000:9)
    at Object.enqueue (file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:15018:11)
    at file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:15176:31
    at ReadFileContext.callback (file:///.../npm/node_modules/purs-tidy/bundle/Main/index.js:16296:19)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:314:13)
```

- tidy 0.9
- windows 10, running from `cmd`
- node v.16.15.0

Haven't made any attempt to debug or fix it yet, but will take a look since it's probably windows related if nobody else has reported this yet.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #103

### CODE REVIEW

**Comment by natefaubion** [comment]
What is the actual fix? It’s not immediately apparent to me.

**Comment by garyb** [comment]
Ah, the previous resolution resulted in the drive letter getting duplicated for Windows paths, because using the `pathname` of the `URL` gives: 

- `/W:/GitHub/purescript-tidy/bin/index.js`
 
When that went through the `path.resolve` it became

- `W:\W:\GitHub\purescript-tidy`

I found the construction I used in here by looking up how to reproduce `__dirname` in ES modules. Apparently the `URL` constructor resolves the first argument path against the second argument base URL, which is why it works with the `".."` in there. And I guess the main difference is `fileURLToPath` is a system-aware version of reading the `pathname` basically.

I had also tried a version where instead of using `pathname` I sliced the `file:///` prefix from the `import.meta.url` and worked with that, which also seemed to do the job, but this seems like the more correct approach, since maybe there are unforeseen edge cases in my first attempt.

**Comment by garyb** [comment]
Bump? (I acknowledge that me bumping an issue is ridiculous given my usual response times, but...)

**Comment by natefaubion** [comment]
Sorry, totally forgot. I’ll be back at my keyboard in a couple days, and I’ll try to release this!

**Comment by natefaubion** [comment]
Thanks! This was published as v0.9.1.

**Comment by garyb** [comment]
Updated via npm and it works a treat again. :+1:

**Pull request merged**
